config/routes.rb
Rails.application.routes.draw do

  devise_for :users, only: [:new, :create]

  resources :users, only: [] do
    resources :profiles
  end

 get '/posts/search' => 'posts#search'

  resources :posts  

  resources :profiles do 
    resources :reviews 
  end 

  resources :topics do 
    resources :posts 
  end 

  devise_for :users, :controllers => {registrations: 'devise/registrations'}

  get '/looking_for', to: 'posts#looking_for'
  get '/offering', to: 'posts#offering'
  get :send_contact_email, to: 'email#send_contact_email', as: :send_contact_email

  get '/about', to: 'welcome#about'
  get '/contact', to: 'welcome#contact'

  root 'welcome#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	has_many :reviews, dependent: :destroy 

	 # This method associates the attribute ":avatar" with a file attachment
	 has_attached_file :avatar, styles: {
	 	thumb: '100x100>',
	 	square: '200x200#',
	 	medium: '300x300>'
	 }
	 
  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def new 
    @user = User.find params[:user_id]
    @profile = Profile.new
  end 

#will have to change 
  def index
    @profiles = Profile.new  
  end

  def show 
    @profile = Profile.find params[:id]
    user_id = @profile.user_id
    @user = User.find(user_id)
    @posts = @user.posts.all 
  end

  def edit 
    @profile = Profile.find params[:id]
    user_id = @profile.user_id
    @user = User.find(user_id)
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    if @profile.save 
      redirect_to user_profile_path(current_user, @profile)
    else 
      render 'new'
    end 
  end

  def update 
    @profile = Profile.find(params[:id])
    user_id = @profile.user_id
    @user = User.find(user_id)
     if @profile.update(profile_params)
        redirect_to user_profile_path(@user, @profile)
      else
        render 'edit'
      end
  end 

  def destroy
      @profile = Profile.find params[:id]
      @profile.destroy
      redirect_to root_path
  end

  private
    def profile_params
      params.require(:profile).permit(:name, :location, :biography, :phone_number, :user_id, :image_url)
   end
end 

app/views/profiles/_form.html.erb
<div class="box">
  <div class="row">
    <div class="reviewform">
      <div class="col-lg-6 col-lg-offset-3">



        <%= simple_form_for  @profile, html: {multipart: true} do |f| %>

        <p>
          <%= f.input :name, label: "Username:" %><br>
        </p>
        <p>
          <%= f.input :image_url, label: "Image URL:" %><br>
        </p>
        <p>
          <%= f.input :location , label: "Location:" %><br>
        </p>
        <p>
          <%= f.input :biography, label: "Biography:" %><br>
        </p>
        <p>
          <%= f.input :phone_number, label: "Phone Number:", :class => "textbox"%><br>
        </p>
        <p>
         <%= f.button :submit, :class => "form-button"  %>
       </p>
       <% end %>

     </div>
   </div>
 </div>
</div>

app/views/profiles/_profile.html.erb
<br><br><br>

<div class="row">
	<div class="box">
		<div class="col-lg-12 text-center">
			<div class="post-heading">

				<div class="col-lg-12">
					<div class="profile-heading">
						<hr>
						<h1><strong><%= @profile.name %></strong> </h1>
						<hr>
					</div>
				</div>
				<img src="<%= @profile.image_url %>", alt ="", width="250">
				<% if current_user.id == @profile.user_id %>
				<h3><b>EMAIL</b></h3>
				<p><%= @user.email %></p>
				<% end %>
				<br>
				<h3><b>LOCATION</b></h3>
				<p><%= @profile.location %></p>
				<br>
				<h3><b>BIOGRAPHY</b></h3>
				<p><%= @profile.biography %></p>
				<br>
				<h3><b>PHONE NUMBER</b></h3>
				<p><%= @profile.phone_number %></p>
				<br> <br>

				<% if current_user = @profile.user %>
				<p><%= link_to "Edit Profile", edit_user_profile_path(@profile.user_id, @profile.id), class: 'link-to-text-color' %> </p>
				<% end %>
				<br> <br>
			</div>
		</div>
	</div>
	<div class="box">
		<div class="col-lg-12 text-center">
			<div class="post-heading">
				<h2>Posts: </h2>
				<hr>
				<% @posts.each do |post| %>
				<h3><%= link_to post.title, post_path(post), class: 'link-to-text-color' %></h3>
				<% end %>
			</ul>
		</div>
	</div>
</div>
<br><br>
<div class="box">
	<div class="col-lg-12 text-center">
		<div class="post-heading">
			<h2>Reviews:</h2>
			<hr>
			<%= render @profile.reviews %>
			<% if user_signed_in? %>

			<div class="row">
			
<div class="col-lg-3"> .</div>
					<div class="col-lg-6">

						<h3>Add a review:</h3>
						<% @review = Review.new %>
						<%= render 'reviews/form' %>
						<% end %>
					</div>
					<div class="col-lg-3"> .</div>
				
			</div>

app/views/profiles/edit.html.erb
<!-- MAIN IMAGE SECTION -->
<div id="serviceswrap">
	<div class="container">
		<div class="box">
			<div class="row">
				<div class="col-lg-6 col-lg-offset-3">
					<h2>Edit Profile
					</h2>
				</div>
			</div><!-- row -->
			<%= render 'form' %>
		</div>
	</div><!-- /container -->
</div><!-- /headerwrap -->

app/views/profiles/new.html.erb
	<div class="row">
		<div class="box">
			<div class="col-lg-12">

				<div class="row">
					
					<div class="col-md-4"></div>
					<div class="col-md-4"><h2>Create a Profile
					</h2><br><%= render 'form' %></div>
					<div class="col-md-4"></div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/profiles/show.html.erb
				<%= render 'profile' %>