config/routes.rb
Rails.application.routes.draw do

  devise_for :users, only: [:new, :create]

  resources :users, only: [] do
    resources :profiles
  end

 get '/posts/search' => 'posts#search'

  resources :posts  

  resources :profiles do 
    resources :reviews 
  end 

  resources :topics do 
    resources :posts 
  end 

  devise_for :users, :controllers => {registrations: 'devise/registrations'}

  get '/looking_for', to: 'posts#looking_for'
  get '/offering', to: 'posts#offering'
  get :send_contact_email, to: 'email#send_contact_email', as: :send_contact_email

  get '/about', to: 'welcome#about'
  get '/contact', to: 'welcome#contact'

  root 'welcome#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController 

	def index 
		@topics = Topic.all 
	end 

	def show 
		@all_posts = Post.all 
		@topic = Topic.find params[:id]
		@posts = []
		@all_posts.each do |post|
			if post.topic == @topic 
				@posts << post 
			end 
		end 
	end 
end 

app/views/topics/index.html.erb
    <br>
    <br>
    <br>
    <br>


    <div class="row">
    	<div class="box">
    		<div class="col-lg-12 text-center">
    			<hr>
    			 <h1 class="page-title"><strong>Topics</strong></h1>
    			<hr>
    		</div>
    	</div>
    </div>

    <div class="row">
        	<div class="box">
    			<div class="col-lg-12 text-center">
    				<div class="topics">
    					<h3><% @topics.each do |topic| %>
    						<%= link_to topic.name, topic_path(topic), class: 'link-to-text-color' %>
    						<hr>

    						<% end %></h3>
    					</div>
    				</div>
    			</div>
    		</div>
    	</div>

app/views/topics/show.html.erb
<br><br><br>
<div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">
                        <strong><%= @topic.name %></strong>
                    </h2>
                    <hr>
         
                	<% @posts.each do |post| %>
                      <% 
    user_id = post.user_id %>
   <% @user = User.find(user_id) %>
  <%  @profile = @user.profile %>
                    <h2><%= link_to post.title, post_path(post), class: 'link-to-text-color' %>
                        <br>
                        <small><%= @profile.name%></small>
                    </h2>
                    <p><%= post.description %></p>
                    
                    <hr>
                </div>
                <% end %>
                
            </div>
        </div>

    </div>
    <!-- /.container -->