config/routes.rb
Rails.application.routes.draw do

  devise_for :users, only: [:new, :create]

  resources :users, only: [] do
    resources :profiles
  end

 get '/posts/search' => 'posts#search'

  resources :posts  

  resources :profiles do 
    resources :reviews 
  end 

  resources :topics do 
    resources :posts 
  end 

  devise_for :users, :controllers => {registrations: 'devise/registrations'}

  get '/looking_for', to: 'posts#looking_for'
  get '/offering', to: 'posts#offering'
  get :send_contact_email, to: 'email#send_contact_email', as: :send_contact_email

  get '/about', to: 'welcome#about'
  get '/contact', to: 'welcome#contact'

  root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic 

  def self.search(query)
  	where("title ILIKE ? OR description ILIKE ?", "%#{query}%", "%#{query}%")
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new 
    @post = Post.new
  end 
 
  def index
    @posts = Post.all 
    
  end

  def search
    @posts = Post.search(params[:search])
    render :index
  end


  def looking_for 
    @all_posts = Post.all
    @posts = []
    @all_posts.each do |post|
      if post.looking_for == false
        @posts << post 
      end 
    end 
    @posts = @posts.reverse
  end 

  def offering  
    @all_posts = Post.all
    @posts = []
    @all_posts.each do |post|
      if post.looking_for 
        @posts << post 
      end 
    end 
    @posts = @posts.reverse
  end 

  def show 
    @post = Post.find params[:id]
    user_id = @post.user_id
    @user = User.find(user_id)
    @profile = @user.profile 
  end

  def edit 
    @post = Post.find params[:id]
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save 
      redirect_to post_path(@post)
    else 
      render 'new'
    end 
  end

  def update 
    @post = Post.find(params[:id])
     if @post.update(post_params)
        redirect_to @post
      else
        render 'edit'
      end
  end 

  def destroy
      @post = Post.find params[:id]
      @post.destroy
      redirect_to posts_path(current_user)
  end

  private
    def post_params
      params.require(:post).permit(:title, :topic_id, :price, :location, :description, :looking_for)
   end
end 

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>

	<%= f.input :title %>
	<%= f.input :topic_id, :collection => Topic.all %>
	<%= f.input :location %>
	<%= f.input :price %>
	<%= f.input :description %> 
	<p> Please pick one of the options below.</p>
	<%= f.select :looking_for, [['I am looking for this service', true], ['I am offering this service', false]] %>
	<br><br>

	<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
	<div class="row">
		<div class="box">
			<div class="col-lg-12">
				<div class="row">
					<div class="col-md-4"></div>
					<div class="col-md-4"><h2> Edit Post</h2><%= render 'form' %><br><p><%= link_to 'Back', posts_path, class: 'link-to-text-color' %></p></div>
					<div class="col-md-4"></div>
				</div>
			</div>
		</div>
	</div>
</div>
		

app/views/posts/index.html.erb
<br><br>

<div class="container">

    <ol class="breadcrumb">
     
    </ol>

    <div class="row">

      <!-- Article main content -->
      <article class="col-md-12 maincontent">
        <header class="page-header">
<div class="title">
         <h1 class="page-title text-center"><strong>All Posts</strong></h1>
         <h2 class="intro-text">Search All Posts
                </h2>
                <hr>
                <%= form_tag(posts_search_path, :method => "get", id: "search-form") do %>
                <%= text_field_tag :search, params[:search] %>
                <%= submit_tag "Search", :name => nil %>
                <% end %> </h2>
                <hr>
                </div>
          <% @posts.each do |post| %>
                    <% user_id = post.user_id %>
                    <% @user = User.find(user_id) %>
                    <%  @profile = @user.profile %>
        
        </header>
<h2><%= link_to post.title, post_path(post), class: 'link-to-text-color' %></h2>
        <h3><%= @profile.name%></h3>
        <p><%= post.description %></p>
        <hr>
        <%end%>


      </article>
<!-- /.container -



<div class="container">

    <div class="row">
        <div class="box">
            <div class="column-lg-12 text-center">
                <hr>
                <h2 class="intro-text text-center">All
                    <strong>posts</strong>
                </h2>
                <hr>
                <h2 class="intro-text text-center">Search All Posts
                </h2>
                <%= form_tag(posts_search_path, :method => "get", id: "search-form") do %>
                <%= text_field_tag :search, params[:search] %>
                <%= submit_tag "Search", :name => nil %>
                <% end %> </h2>
                <hr>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12 text-center">
                	<% @posts.each do |post| %>
                    <% user_id = post.user_id %>
                    <% @user = User.find(user_id) %>
                    <%  @profile = @user.profile %>
                    <h2><%= link_to post.title, post_path(post), class: 'link-to-text-color' %>
                    </h2>
                    <div class="name"><h3><%= @profile.name%></h3></div>
                    <p><%= post.description %></p>
                    
                    <hr>
                    <% end %>
                </div>
            </div>
        </div>

</div>
    <!-- /.container -->

app/views/posts/looking_for.html.erb
<br><br><br>
<div class="container">

    <ol class="breadcrumb">
     
    </ol>

    <div class="row">

      <!-- Article main content -->
      <article class="col-md-12 maincontent">
        <header class="page-header">
         <h1 class="page-title text-center">What Can You <strong>Learn?</strong></h1>
          <% @posts.each do |post| %>
                    <% user_id = post.user_id %>
                    <% @user = User.find(user_id) %>
                    <%  @profile = @user.profile %>
        
        </header>
<h2><%= link_to post.title, post_path(post), class: 'link-to-text-color' %></h2>
        <h3><%= @profile.name%></h3>
        <p><%= post.description %></p>
<hr>
<%end%>
      </article>
<!-- /.container -->

app/views/posts/new.html.erb
<br><br><br>
	<div class="row">
		<div class="box">
			<div class="col-lg-12">
				<div class="row">
					<div class="col-md-4"></div>
					<div class="col-md-4"><h2> New Post</h2><%= render 'form' %></div>
					<div class="col-md-4"></div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/posts/offering.html.erb
<br><br><br>
<div class="container">

    <ol class="breadcrumb">
     
    </ol>

    <div class="row">

      <!-- Article main content -->
      <article class="col-md-12 maincontent">
        <header class="page-header">
         <h1 class="page-title text-center"><strong>Teach</strong> a Man to Fish...</h1>
          <% @posts.each do |post| %>
                    <% user_id = post.user_id %>
                    <% @user = User.find(user_id) %>
                    <%  @profile = @user.profile %>
        
        </header>
<h2><%= link_to post.title, post_path(post), class: 'link-to-text-color' %></h2>
        <h3><%= @profile.name%></h3>
        <p><%= post.description %></p>
<hr>
<%end%>
      </article>
      <!-- /Article -->

app/views/posts/show.html.erb
<br><br><br>

<div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <div class="post-heading">
                    <hr>
 <div class="col-lg-12 text-center">
<div class="heading">
<h1><%= @post.title %> </h1>
<h2>By: <%= link_to @profile.name, user_profile_path(@profile.user_id, @profile), class: 'link-to-text-color' %></h2>
<hr>
</div>

<% topic = Topic.find(@post.topic_id) %>
<h3><b>TOPIC</b></h3>
		  	<p><%= topic.name %></p>
		  	<br>
		  	<h3><b>LOCATION</b></h3>
		  	<p><%= @post.location %></p>
		  	<br>
		  	<h3><b>PRICE</b></h3>
		  	<p><%= @post.price %></p>
		  	<br>
		  	<h3><b>DESCRIPTION</b></h3>
		  	<p><%= @post.description %></p>

<% if user_signed_in? %>
<h2>
<%= link_to "Send Contact Email", {:controller => "email", :action => "send_contact_email", :post => @post.id }, data: { confirm: 'Are you certain you want to contact this person? Upon clicking yes, we will send the poster an email with your contact information.' }, class: 'link-to-text-color' %></h2>

<br> 
<% if user_signed_in? %>
<% if current_user.id == @post.user_id %>
<%= link_to 'Edit', edit_post_path(@post), class: 'link-to-text-color' %>
  <%= link_to 'Delete', post_path(@post),
               method: :delete, class: 'link-to-text-color',
              data: { confirm: 'Are you sure?' } 
              %>
<% end %>
<% end %>
<%end %>

</div>
</div>
</div>
</div>
</div>