config/routes.rb
Rails.application.routes.draw do

  devise_for :users, only: [:new, :create]

  resources :users, only: [] do
    resources :profiles
  end

 get '/posts/search' => 'posts#search'

  resources :posts  

  resources :profiles do 
    resources :reviews 
  end 

  resources :topics do 
    resources :posts 
  end 

  devise_for :users, :controllers => {registrations: 'devise/registrations'}

  get '/looking_for', to: 'posts#looking_for'
  get '/offering', to: 'posts#offering'
  get :send_contact_email, to: 'email#send_contact_email', as: :send_contact_email

  get '/about', to: 'welcome#about'
  get '/contact', to: 'welcome#contact'

  root 'welcome#index'

end

app/views/layouts/_nav.html.erb
    <div class="navigation"><!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top headroom" >
        <div class="container">
            <div class="navbar-header">
                <!-- Button for smallest screens -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                <a class="navbar-brand"><%= link_to "QuickSkill", root_path, class: 'link-to-home' %></a> <br>
                <% if user_signed_in? && !current_user.profile.nil? %>
    <% url = "Signed in as " + current_user.email %>
    <%= link_to url, user_profile_path(current_user, current_user.profile), class: 'profile-sign-in'  %>
    <% end %>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav pull-right">
           
                 
                    <li><%= link_to "Find By Topic", topics_path %></li>
                            <li><%= link_to "Learn Something", looking_for_path %></li>
                            <li><%= link_to "Teach Something", offering_path %></li>
                               <li><%= link_to " All Posts", posts_path %></li>
                             <br>
                             <% if user_signed_in? %>
            <% if current_user.profile.nil? %> 
            <li><%= link_to "Create A Profile", new_user_profile_path(current_user)  %></li>
            
            <% else %>
            <li><%= link_to "Create A Post", new_post_path(current_user) %></li>
            <li><%= link_to "Visit My Profile", user_profile_path(current_user, current_user.profile)  %></li>
            <% end %>
            <% end %>
                     <li><%= link_to "About Us", about_path %></li>    
                 
                    <% if user_signed_in? %>
                    <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
                        <% else %>
                        <li><%= link_to "Sign up", new_user_registration_path %></li>
                        <li><%= link_to "Login", new_user_session_path %></li>
                        <% end %>
                        </ul>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
    </div>
    <!-- /.navbar -->



	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuickSkill</title>
  	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,700">
  	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  <%= csrf_meta_tags %>
</head>
<body class="home">

     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>


<%= render 'layouts/nav' %>

<%= yield %>
<%= render 'layouts/footer' %>
<%= javascript_include_tag 'application', 'data-turbolinks-eval' => false %>.

</body>
</html>